### ISSUE TITLE
Práctica 3: Diseño de TextBox personalizado

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Ferch0419#2]
[Práctica 3 TextBox personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Ferch0419/files/6344847/Practica.3.TextBox.personalizado.pdf)

**Comment by javiern-778** [comment]
20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
